"""Checker registry, structural checkers, and manifest hashing."""

from __future__ import annotations

import hashlib
import json
import re
from collections.abc import Callable
from dataclasses import dataclass, field
from typing import Awaitable
from typing import Protocol

from app.modules.tasks.models import Submission, WorkstreamTask
from app.modules.tasks.schemas import SubmissionCreate

CHECKER_STATUS_PASSED = "passed"
CHECKER_STATUS_WARNING = "warning"
CHECKER_STATUS_FAILED = "failed"

CHECKER_SEVERITY_INFO = "info"
CHECKER_SEVERITY_LOW = "low"
CHECKER_SEVERITY_MEDIUM = "medium"
CHECKER_SEVERITY_HIGH = "high"
CHECKER_SEVERITY_CRITICAL = "critical"

BLOCKING_SEVERITIES = {CHECKER_SEVERITY_HIGH, CHECKER_SEVERITY_CRITICAL}
ROUTING_PROJECT_SETUP_REQUIRED = "project_setup_required"

HASH_TOKEN_PATTERN = re.compile(r"^sha256:\S+$")
GENERIC_ATTESTATIONS = {"ok", "done", "yes", "i agree", "confirmed"}
CONFIDENTIALITY_TERMS = ("confidential", "private", "client data", "proprietary")
CREDENTIAL_TERMS = ("credential", "secret", "token", "password", "api key")
SOURCE_PLATFORM_TERMS = (
    "source material",
    "source code",
    "platform artifact",
    "copied artifact",
    "copied platform",
)
LOW_QUALITY_GENERATED_PATTERNS = (
    "todo",
    "placeholder",
    "lorem ipsum",
    "sample output",
    "dummy",
    "generated by chatgpt",
    "as an ai language model",
)
FORBIDDEN_EXACT_SEGMENTS = {
    ".env",
    ".git",
    "credential",
    "id_rsa",
    "node_modules",
    "private_key",
    "secret",
    "token",
}
FORBIDDEN_SUFFIXES = (".pem", ".key")


class CheckerNameConflict(ValueError):
    """Raised when duplicate checker names are registered."""


class UnknownChecker(ValueError):
    """Raised when a policy references an unregistered checker."""


class ArtifactManifestError(ValueError):
    """Raised when an artifact manifest cannot be canonicalized."""


@dataclass(frozen=True)
class CheckerOutcome:
    """In-memory checker result before persistence."""

    checker_name: str
    status: str
    severity: str
    message: str
    blocks_review: bool = False
    worker_message: str | None = None
    worker_suggested_fix: str | None = None
    worker_evidence_refs: list[str] = field(default_factory=list)
    worker_visible: bool = True
    metadata: dict = field(default_factory=dict)
    routing_recommendation: str | None = None


@dataclass(frozen=True)
class CheckerContext:
    """Data available to structural checkers."""

    task: WorkstreamTask
    submission: Submission
    required_checker_names: frozenset[str]
    warning_checker_names: frozenset[str]
    blocking_severities: frozenset[str]


class Checker(Protocol):
    """Protocol implemented by registered checkers."""

    name: str

    async def run(self, context: CheckerContext) -> CheckerOutcome:
        """Run the checker against a locked submission context."""


CheckerHandler = Callable[[CheckerContext], Awaitable[CheckerOutcome]]


class FunctionChecker:
    """Checker adapter around a plain callable."""

    def __init__(self, name: str, handler: "CheckerHandler") -> None:
        """Create a named checker.

        Args:
            name: Canonical checker name referenced by checker policies.
            handler: Function that evaluates a checker context.
        """
        self.name = name
        self._handler = handler

    async def run(self, context: CheckerContext) -> CheckerOutcome:
        """Run the wrapped checker handler."""
        return await self._handler(context)


class CheckerRegistry:
    """Registry of canonical checker implementations."""

    def __init__(self) -> None:
        """Create an empty checker registry."""
        self._checkers: dict[str, Checker] = {}

    def register(self, checker: Checker) -> None:
        """Register one checker implementation by canonical name.

        Args:
            checker: Checker implementation to register.

        Raises:
            CheckerNameConflict: If another checker already owns the same name.
        """
        if checker.name in self._checkers:
            raise CheckerNameConflict(f"checker already registered: {checker.name}")
        self._checkers[checker.name] = checker

    def require_registered(self, checker_names: set[str]) -> None:
        """Validate that all policy checker names have implementations.

        Args:
            checker_names: Checker names from locked checker policy.

        Raises:
            UnknownChecker: If any checker name is not registered.
        """
        missing = sorted(checker_names.difference(self._checkers))
        if missing:
            raise UnknownChecker(f"unregistered checker policy names: {', '.join(missing)}")

    async def run(
        self,
        context: CheckerContext,
        checker_names: list[str],
    ) -> list[CheckerOutcome]:
        """Run checkers in policy order.

        Args:
            context: Locked checker context.
            checker_names: Canonical checker names to execute.

        Returns:
            Checker outcomes in the same order as ``checker_names``.
        """
        self.require_registered(set(checker_names))
        return [await self._checkers[name].run(context) for name in checker_names]

    def names(self) -> set[str]:
        """Return all registered checker names."""
        return set(self._checkers)


def canonical_artifact_manifest_hash(manifest: list[dict]) -> str:
    """Hash a submission artifact manifest using Workstream canonical JSON.

    Args:
        manifest: Artifact hash entries persisted on a submission.

    Returns:
        SHA-256 digest prefixed with ``sha256:``.

    Raises:
        ArtifactManifestError: If duplicate artifacts or invalid entries are present.
    """
    seen_artifacts: set[str] = set()
    canonical_entries: list[dict] = []
    for entry in manifest:
        artifact = str(entry.get("artifact", "")).strip()
        artifact_hash = str(entry.get("hash", "")).strip()
        if not artifact or not artifact_hash:
            raise ArtifactManifestError("artifact manifest entries require artifact and hash")
        if artifact in seen_artifacts:
            raise ArtifactManifestError(f"duplicate artifact in manifest: {artifact}")
        seen_artifacts.add(artifact)
        canonical_entries.append(
            {
                "artifact": artifact,
                "hash": artifact_hash,
                "notes": entry.get("notes"),
                "size_bytes": entry.get("size_bytes"),
            }
        )
    encoded = json.dumps(
        sorted(canonical_entries, key=lambda item: (item["artifact"], item["hash"])),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
    ).encode("utf-8")
    return f"sha256:{hashlib.sha256(encoded).hexdigest()}"


async def pre_submit_static_feedback(
    task: WorkstreamTask,
    payload: SubmissionCreate,
) -> list[CheckerOutcome]:
    """Run non-authoritative structural checks before a submission is created.

    Args:
        task: Task receiving the draft packet.
        payload: Draft submission packet payload.

    Returns:
        Worker-facing checker feedback items. These are not durable gate records.
    """
    outcomes: list[CheckerOutcome] = []
    manifest = [entry.model_dump() for entry in payload.artifact_hash_manifest]
    evidence_items = [entry.model_dump() for entry in payload.evidence_items]
    outcomes.append(_packet_shape_outcome(payload.summary, payload.package_hash, manifest))
    outcomes.append(_evidence_presence_outcome(len(payload.evidence_items), task.required_evidence))
    outcomes.append(_evidence_integrity_outcome(manifest, evidence_items))
    outcomes.append(_required_files_outcome(task.required_files, manifest))
    outcomes.append(_forbidden_files_outcome(manifest, evidence_items))
    outcomes.append(_confidentiality_attestation_outcome(payload.worker_attestation))
    low_quality = _low_quality_generated_artifacts_outcome(
        payload.summary,
        payload.worker_attestation,
        manifest,
        evidence_items,
    )
    if low_quality is not None:
        outcomes.append(low_quality)
    return outcomes


def _pass(name: str, message: str, *, metadata: dict | None = None) -> CheckerOutcome:
    """Build a passing checker outcome."""
    return CheckerOutcome(
        checker_name=name,
        status=CHECKER_STATUS_PASSED,
        severity=CHECKER_SEVERITY_INFO,
        message=message,
        worker_message=message,
        metadata=metadata or {},
    )


def _fail(
    name: str,
    message: str,
    suggested_fix: str,
    *,
    metadata: dict | None = None,
    worker_visible: bool = True,
    routing_recommendation: str | None = None,
) -> CheckerOutcome:
    """Build a worker-fixable failing checker outcome."""
    return CheckerOutcome(
        checker_name=name,
        status=CHECKER_STATUS_FAILED,
        severity=CHECKER_SEVERITY_HIGH,
        message=message,
        blocks_review=True,
        worker_message=message if worker_visible else None,
        worker_suggested_fix=suggested_fix if worker_visible else None,
        worker_visible=worker_visible,
        metadata=metadata or {},
        routing_recommendation=routing_recommendation,
    )


def _warning(name: str, message: str, *, metadata: dict | None = None) -> CheckerOutcome:
    """Build a non-blocking warning checker outcome."""
    return CheckerOutcome(
        checker_name=name,
        status=CHECKER_STATUS_WARNING,
        severity=CHECKER_SEVERITY_MEDIUM,
        message=message,
        blocks_review=False,
        worker_message=message,
        worker_visible=True,
        metadata=metadata or {},
    )


def _packet_shape_outcome(summary: str, package_hash: str, manifest: list[dict]) -> CheckerOutcome:
    """Validate required packet fields shared by pre-submit and durable checks."""
    missing: list[str] = []
    if not summary.strip():
        missing.append("summary")
    if not package_hash.strip():
        missing.append("package_hash")
    if not manifest:
        missing.append("artifact_hash_manifest")
    if missing:
        return _fail(
            "check_submission_packet",
            f"Submission packet is missing required fields: {', '.join(missing)}.",
            "Add the missing packet fields before submitting.",
            metadata={"missing_fields": missing},
        )
    return _pass("check_submission_packet", "Submission packet contains required fields.")


def _hash_token_is_valid(value: str | None) -> bool:
    """Return whether a hash value has the Chunk 8 structural token shape."""
    if value is None:
        return False
    return bool(HASH_TOKEN_PATTERN.match(value.strip()))


def _normalize_artifact_path(value: str) -> str:
    """Normalize an artifact path for checker comparison.

    Raises:
        ValueError: If the path is empty, absolute, or contains traversal segments.
    """
    normalized = re.sub(r"/+", "/", value.strip().replace("\\", "/"))
    if normalized.startswith("./"):
        normalized = normalized[2:]
    if not normalized or normalized.startswith("/"):
        raise ValueError("artifact path must be relative and non-empty")
    segments = normalized.split("/")
    if any(segment in {"", ".", ".."} for segment in segments):
        raise ValueError("artifact path must not contain empty or traversal segments")
    return normalized


def _evidence_integrity_outcome(manifest: list[dict], evidence_items: list[dict]) -> CheckerOutcome:
    """Validate manifest and evidence reference structural integrity."""
    try:
        artifact_names = []
        invalid_artifacts = []
        for entry in manifest:
            artifact = str(entry.get("artifact", ""))
            artifact_names.append(_normalize_artifact_path(artifact))
            if not _hash_token_is_valid(str(entry.get("hash", ""))):
                invalid_artifacts.append(artifact)
        manifest_hash = canonical_artifact_manifest_hash(manifest)
    except (ArtifactManifestError, ValueError) as exc:
        return _fail(
            "check_evidence_integrity",
            "Artifact manifest contains invalid or duplicate entries.",
            "Use relative artifact paths, one unique artifact entry per artifact, and a sha256 hash token.",
            metadata={"integrity_error": str(exc)},
        )
    if invalid_artifacts:
        return _fail(
            "check_evidence_integrity",
            "Artifact manifest contains malformed hash references.",
            "Use hash values shaped like sha256:<token> for each artifact.",
            metadata={"invalid_artifact_count": len(invalid_artifacts)},
        )

    missing_evidence_hash_labels = [
        str(item.get("label", "")).strip() or str(index)
        for index, item in enumerate(evidence_items, start=1)
        if item.get("uri") and not _hash_token_is_valid(item.get("hash"))
    ]
    if missing_evidence_hash_labels:
        return _fail(
            "check_evidence_integrity",
            "Evidence object references are missing structural hash tokens.",
            "Add sha256:<token> hash values for evidence objects stored in local, R2, or S3 storage.",
            metadata={"missing_evidence_hash_count": len(missing_evidence_hash_labels)},
        )
    return _pass(
        "check_evidence_integrity",
        "Artifact manifest and evidence references are structurally valid.",
        metadata={"artifact_manifest_hash": manifest_hash, "artifact_count": len(artifact_names)},
    )


def _evidence_presence_outcome(
    evidence_count: int,
    required_evidence: list[str],
) -> CheckerOutcome:
    """Validate that required-evidence tasks include evidence rows."""
    if required_evidence and evidence_count == 0:
        return _fail(
            "check_evidence_present",
            "Submission is missing required evidence references.",
            "Attach evidence items required by the task before submitting.",
            metadata={"required_evidence": required_evidence},
        )
    return _pass("check_evidence_present", "Submission includes required evidence references.")


def _required_files_outcome(required_files: list[str], manifest: list[dict]) -> CheckerOutcome:
    """Validate that required files are represented in the artifact manifest."""
    if not required_files:
        return _pass("check_required_files", "Task does not require specific files.")
    try:
        required = {_normalize_artifact_path(path) for path in required_files}
        provided = {
            _normalize_artifact_path(str(entry.get("artifact", "")))
            for entry in manifest
            if str(entry.get("artifact", "")).strip()
        }
    except ValueError as exc:
        return _fail(
            "check_required_files",
            str(exc),
            "Use relative artifact paths without traversal segments.",
        )
    missing = sorted(required.difference(provided))
    if missing:
        return _fail(
            "check_required_files",
            "Submission is missing required artifact files.",
            "Add every file required by the task to the artifact hash manifest.",
            metadata={"missing_required_files": missing},
        )
    return _pass("check_required_files", "Submission includes required artifact files.")


def _forbidden_files_outcome(manifest: list[dict], evidence_items: list[dict]) -> CheckerOutcome:
    """Validate artifact and evidence paths against default forbidden path patterns."""
    paths = [str(entry.get("artifact", "")) for entry in manifest]
    paths.extend(str(item.get("uri", "")) for item in evidence_items if item.get("uri"))
    forbidden_categories: set[str] = set()
    for path in paths:
        try:
            normalized = _normalize_artifact_path(path)
        except ValueError:
            continue
        lowered_segments = [segment.lower() for segment in normalized.split("/")]
        filename = lowered_segments[-1]
        if any(segment in FORBIDDEN_EXACT_SEGMENTS for segment in lowered_segments):
            forbidden_categories.add("forbidden_path_segment")
        if filename.endswith(FORBIDDEN_SUFFIXES):
            forbidden_categories.add("forbidden_file_suffix")
    if forbidden_categories:
        return _fail(
            "check_forbidden_files",
            "Submission includes forbidden artifact or evidence path patterns.",
            "Remove forbidden files or evidence references before review.",
            metadata={"forbidden_categories": sorted(forbidden_categories)},
        )
    return _pass("check_forbidden_files", "Submission does not include default forbidden paths.")


def _confidentiality_attestation_outcome(worker_attestation: str) -> CheckerOutcome:
    """Validate the deterministic Chunk 8 confidentiality attestation minimum."""
    normalized = " ".join(worker_attestation.strip().lower().split())
    has_required_length = len(normalized) >= 40
    has_non_generic_text = normalized not in GENERIC_ATTESTATIONS
    has_confidentiality = any(term in normalized for term in CONFIDENTIALITY_TERMS)
    has_credentials = any(term in normalized for term in CREDENTIAL_TERMS)
    has_source_platform = any(term in normalized for term in SOURCE_PLATFORM_TERMS)
    if not all(
        [
            has_required_length,
            has_non_generic_text,
            has_confidentiality,
            has_credentials,
            has_source_platform,
        ]
    ):
        return _fail(
            "check_confidentiality_attestation",
            "Submission is missing the required confidentiality attestation.",
            (
                "Attest that the submission excludes confidential data, credentials, "
                "and copied source or platform artifacts."
            ),
            metadata={
                "has_required_length": has_required_length,
                "has_confidentiality_term": has_confidentiality,
                "has_credential_term": has_credentials,
                "has_source_or_platform_term": has_source_platform,
            },
        )
    return _pass(
        "check_confidentiality_attestation",
        "Submission includes the required confidentiality attestation.",
    )


def _low_quality_generated_artifacts_outcome(
    summary: str,
    worker_attestation: str,
    manifest: list[dict],
    evidence_items: list[dict],
) -> CheckerOutcome | None:
    """Warn on obvious placeholder or generated-output signals."""
    haystack_parts = [summary, worker_attestation]
    haystack_parts.extend(str(entry.get("artifact", "")) for entry in manifest)
    haystack_parts.extend(str(entry.get("notes", "")) for entry in manifest)
    haystack_parts.extend(str(item.get("label", "")) for item in evidence_items)
    haystack = "\n".join(haystack_parts).lower()
    matched = sorted(pattern for pattern in LOW_QUALITY_GENERATED_PATTERNS if pattern in haystack)
    if not matched:
        return None
    return _warning(
        "check_low_quality_generated_artifacts",
        "Submission contains placeholder or generic generated-output signals.",
        metadata={"matched_pattern_count": len(matched), "matched_categories": matched},
    )


async def check_submission_packet(context: CheckerContext) -> CheckerOutcome:
    """Validate required submission packet fields after the packet is locked."""
    return _packet_shape_outcome(
        context.submission.summary,
        context.submission.package_hash,
        context.submission.artifact_hash_manifest,
    )


async def check_policy_context_present(context: CheckerContext) -> CheckerOutcome:
    """Validate that the submission carries all locked guide and policy versions."""
    missing = [
        name
        for name, value in {
            "locked_guide_version": context.submission.locked_guide_version,
            "locked_checker_policy_version": context.submission.locked_checker_policy_version,
            "locked_review_policy_version": context.submission.locked_review_policy_version,
            "locked_revision_policy_version": context.submission.locked_revision_policy_version,
            "locked_payment_policy_version": context.submission.locked_payment_policy_version,
        }.items()
        if not value
    ]
    if missing:
        return _fail(
            "check_policy_context_present",
            "Submission is missing locked guide or policy context.",
            "A project manager must re-screen the task before review can continue.",
            metadata={"missing_context": missing},
            worker_visible=False,
            routing_recommendation=ROUTING_PROJECT_SETUP_REQUIRED,
        )
    return _pass("check_policy_context_present", "Submission has locked guide and policy context.")


async def check_evidence_integrity(context: CheckerContext) -> CheckerOutcome:
    """Validate artifact manifest and evidence reference structural integrity."""
    evidence_items = [
        {
            "label": item.label,
            "uri": item.uri,
            "hash": item.hash,
            "type": item.type,
        }
        for item in context.submission.evidence_items
    ]
    return _evidence_integrity_outcome(context.submission.artifact_hash_manifest, evidence_items)


async def check_evidence_present(context: CheckerContext) -> CheckerOutcome:
    """Validate that evidence references exist when the task requires evidence."""
    return _evidence_presence_outcome(
        len(context.submission.evidence_items),
        context.task.required_evidence,
    )


async def check_acceptance_criteria_present(context: CheckerContext) -> CheckerOutcome:
    """Validate that task setup includes reviewable acceptance criteria."""
    if not (context.task.acceptance_criteria or "").strip():
        return _fail(
            "check_acceptance_criteria_present",
            "Task is not review-ready because acceptance criteria are missing.",
            "A project manager must add reviewable acceptance criteria before review can continue.",
            worker_visible=False,
            routing_recommendation=ROUTING_PROJECT_SETUP_REQUIRED,
        )
    return _pass(
        "check_acceptance_criteria_present",
        "Task includes reviewable acceptance criteria.",
    )


async def check_required_files(context: CheckerContext) -> CheckerOutcome:
    """Validate required task files against the artifact manifest."""
    return _required_files_outcome(
        context.task.required_files,
        context.submission.artifact_hash_manifest,
    )


async def check_forbidden_files(context: CheckerContext) -> CheckerOutcome:
    """Validate artifact and evidence paths against forbidden path patterns."""
    evidence_items = [
        {
            "label": item.label,
            "uri": item.uri,
            "hash": item.hash,
            "type": item.type,
        }
        for item in context.submission.evidence_items
    ]
    return _forbidden_files_outcome(context.submission.artifact_hash_manifest, evidence_items)


async def check_confidentiality_attestation(context: CheckerContext) -> CheckerOutcome:
    """Validate the worker confidentiality attestation."""
    return _confidentiality_attestation_outcome(context.submission.worker_attestation)


async def check_low_quality_generated_artifacts(context: CheckerContext) -> CheckerOutcome:
    """Warn on obvious placeholder or generated-output signals."""
    evidence_items = [
        {
            "label": item.label,
            "uri": item.uri,
            "hash": item.hash,
            "type": item.type,
        }
        for item in context.submission.evidence_items
    ]
    outcome = _low_quality_generated_artifacts_outcome(
        context.submission.summary,
        context.submission.worker_attestation,
        context.submission.artifact_hash_manifest,
        evidence_items,
    )
    return outcome or _pass(
        "check_low_quality_generated_artifacts",
        "Submission does not contain obvious generated-output placeholder signals.",
    )


def default_checker_registry() -> CheckerRegistry:
    """Create the built-in checker registry for v0.1 structural checks."""
    registry = CheckerRegistry()
    registry.register(FunctionChecker("check_submission_packet", check_submission_packet))
    registry.register(FunctionChecker("check_policy_context_present", check_policy_context_present))
    registry.register(
        FunctionChecker("check_acceptance_criteria_present", check_acceptance_criteria_present)
    )
    registry.register(FunctionChecker("check_evidence_present", check_evidence_present))
    registry.register(FunctionChecker("check_evidence_integrity", check_evidence_integrity))
    registry.register(FunctionChecker("check_required_files", check_required_files))
    registry.register(FunctionChecker("check_forbidden_files", check_forbidden_files))
    registry.register(
        FunctionChecker("check_confidentiality_attestation", check_confidentiality_attestation)
    )
    registry.register(
        FunctionChecker(
            "check_low_quality_generated_artifacts",
            check_low_quality_generated_artifacts,
        )
    )
    return registry
